In [1]:
import pandas as pd
base = pd.read_csv('house_prices.csv')
base.head()

id             date     price  ...     long  sqft_living15  sqft_lot15
0  7129300520  20141013T000000  221900.0  ... -122.257           1340        5650
1  6414100192  20141209T000000  538000.0  ... -122.319           1690        7639
2  5631500400  20150225T000000  180000.0  ... -122.233           2720        8062
3  2487200875  20141209T000000  604000.0  ... -122.393           1360        5000
4  1954400510  20150218T000000  510000.0  ... -122.045           1800        7503

[5 rows x 21 columns]

In [2]:
base.columns

Index(['id', 'date', 'price', 'bedrooms', 'bathrooms', 'sqft_living',
       'sqft_lot', 'floors', 'waterfront', 'view', 'condition', 'grade',
       'sqft_above', 'sqft_basement', 'yr_built', 'yr_renovated', 'zipcode',
       'lat', 'long', 'sqft_living15', 'sqft_lot15'],
      dtype='object')

In [3]:
colunas_usadas = ['price', 'bedrooms', 'bathrooms', 'sqft_living',
       'sqft_lot', 'floors', 'waterfront', 'view', 'condition', 'grade',
       'sqft_above', 'sqft_basement', 'yr_built', 'yr_renovated', 'zipcode',
       'lat', 'long']

In [4]:
colunas_usadas

['price',
 'bedrooms',
 'bathrooms',
 'sqft_living',
 'sqft_lot',
 'floors',
 'waterfront',
 'view',
 'condition',
 'grade',
 'sqft_above',
 'sqft_basement',
 'yr_built',
 'yr_renovated',
 'zipcode',
 'lat',
 'long']

In [5]:
base = pd.read_csv('house_prices.csv', usecols = colunas_usadas)

In [6]:
base.head()

price  bedrooms  bathrooms  ...  zipcode      lat     long
0  221900.0         3       1.00  ...    98178  47.5112 -122.257
1  538000.0         3       2.25  ...    98125  47.7210 -122.319
2  180000.0         2       1.00  ...    98028  47.7379 -122.233
3  604000.0         4       3.00  ...    98136  47.5208 -122.393
4  510000.0         3       2.00  ...    98074  47.6168 -122.045

[5 rows x 17 columns]

In [7]:
from sklearn.preprocessing import MinMaxScaler
scaler_x = MinMaxScaler()
base[['bedrooms', 'bathrooms', 'sqft_living',
       'sqft_lot', 'floors', 'waterfront', 'view', 'condition', 'grade',
       'sqft_above', 'sqft_basement', 'yr_built', 'yr_renovated', 'zipcode',
       'lat', 'long']] = scaler_x.fit_transform(base[['bedrooms', 'bathrooms', 'sqft_living',
       'sqft_lot', 'floors', 'waterfront', 'view', 'condition', 'grade',
       'sqft_above', 'sqft_basement', 'yr_built', 'yr_renovated', 'zipcode',
       'lat', 'long']])

In [8]:
base.head()

price  bedrooms  bathrooms  ...   zipcode       lat      long
0  221900.0  0.090909    0.12500  ...  0.893939  0.571498  0.217608
1  538000.0  0.090909    0.28125  ...  0.626263  0.908959  0.166113
2  180000.0  0.060606    0.12500  ...  0.136364  0.936143  0.237542
3  604000.0  0.121212    0.37500  ...  0.681818  0.586939  0.104651
4  510000.0  0.090909    0.25000  ...  0.368687  0.741354  0.393688

[5 rows x 17 columns]

In [9]:
scaler_y = MinMaxScaler()
base[['price']] = scaler_y.fit_transform(base[['price']])

In [10]:
base.head()

price  bedrooms  bathrooms  ...   zipcode       lat      long
0  0.019266  0.090909    0.12500  ...  0.893939  0.571498  0.217608
1  0.060721  0.090909    0.28125  ...  0.626263  0.908959  0.166113
2  0.013770  0.060606    0.12500  ...  0.136364  0.936143  0.237542
3  0.069377  0.121212    0.37500  ...  0.681818  0.586939  0.104651
4  0.057049  0.090909    0.25000  ...  0.368687  0.741354  0.393688

[5 rows x 17 columns]

In [11]:
X = base.drop('price', axis = 1)
y = base.price

In [12]:
X.head()

bedrooms  bathrooms  sqft_living  ...   zipcode       lat      long
0  0.090909    0.12500     0.067170  ...  0.893939  0.571498  0.217608
1  0.090909    0.28125     0.172075  ...  0.626263  0.908959  0.166113
2  0.060606    0.12500     0.036226  ...  0.136364  0.936143  0.237542
3  0.121212    0.37500     0.126038  ...  0.681818  0.586939  0.104651
4  0.090909    0.25000     0.104906  ...  0.368687  0.741354  0.393688

[5 rows x 16 columns]

In [13]:
type(X)

pandas.core.frame.DataFrame

In [14]:
y.head()

0    0.019266
1    0.060721
2    0.013770
3    0.069377
4    0.057049
Name: price, dtype: float64

In [15]:
type(y)

pandas.core.series.Series

In [16]:
previsores_colunas = colunas_usadas[1:17]
previsores_colunas

['bedrooms',
 'bathrooms',
 'sqft_living',
 'sqft_lot',
 'floors',
 'waterfront',
 'view',
 'condition',
 'grade',
 'sqft_above',
 'sqft_basement',
 'yr_built',
 'yr_renovated',
 'zipcode',
 'lat',
 'long']

In [17]:
import tensorflow as tf
tf.random.set_seed(42)
tf.__version__

'2.3.0'

In [18]:
colunas = [tf.feature_column.numeric_column(key = c) for c in previsores_colunas]

In [19]:
print(colunas[10])

NumericColumn(key='sqft_basement', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None)


In [20]:
from sklearn.model_selection import train_test_split
X_treinamento, X_teste, y_treinamento, y_teste = train_test_split(X, y, test_size = 0.3, random_state = 42)

In [21]:
X_treinamento.shape

(15129, 16)

In [22]:
y_treinamento.shape

(15129,)

In [23]:
X_teste.shape

(6484, 16)

In [24]:
def make_input_fn(X, y = None, num_epochs = None, shuffle = True, batch_size = 32):
    def input_function():
        ds = tf.data.Dataset.from_tensor_slices((dict(X), y))
        if shuffle:
            ds = ds.shuffle(1000)
        ds = ds.batch(batch_size).repeat(num_epochs)
        return ds
    return input_function

In [25]:
# Exemplo de criação do dataset a partir do dataframe
ds = tf.data.Dataset.from_tensor_slices((dict(X_treinamento), y_treinamento))
ds

<TensorSliceDataset shapes: ({bedrooms: (), bathrooms: (), sqft_living: (), sqft_lot: (), floors: (), waterfront: (), view: (), condition: (), grade: (), sqft_above: (), sqft_basement: (), yr_built: (), yr_renovated: (), zipcode: (), lat: (), long: ()}, ()), types: ({bedrooms: tf.float64, bathrooms: tf.float64, sqft_living: tf.float64, sqft_lot: tf.float64, floors: tf.float64, waterfront: tf.float64, view: tf.float64, condition: tf.float64, grade: tf.float64, sqft_above: tf.float64, sqft_basement: tf.float64, yr_built: tf.float64, yr_renovated: tf.float64, zipcode: tf.float64, lat: tf.float64, long: tf.float64}, tf.float64)>

In [26]:
funcao_treinamento = make_input_fn(X_treinamento, y_treinamento)

In [27]:
# Exemplo de chamada da `funcao_treinamento()`
funcao_treinamento()

<RepeatDataset shapes: ({bedrooms: (None,), bathrooms: (None,), sqft_living: (None,), sqft_lot: (None,), floors: (None,), waterfront: (None,), view: (None,), condition: (None,), grade: (None,), sqft_above: (None,), sqft_basement: (None,), yr_built: (None,), yr_renovated: (None,), zipcode: (None,), lat: (None,), long: (None,)}, (None,)), types: ({bedrooms: tf.float64, bathrooms: tf.float64, sqft_living: tf.float64, sqft_lot: tf.float64, floors: tf.float64, waterfront: tf.float64, view: tf.float64, condition: tf.float64, grade: tf.float64, sqft_above: tf.float64, sqft_basement: tf.float64, yr_built: tf.float64, yr_renovated: tf.float64, zipcode: tf.float64, lat: tf.float64, long: tf.float64}, tf.float64)>

In [28]:
funcao_teste = make_input_fn(X_teste, y_teste, num_epochs = 10000, shuffle = False)

In [29]:
config = tf.estimator.RunConfig(tf_random_seed = 42)
regressor = tf.estimator.LinearRegressor(feature_columns = colunas, config = config)

INFO:tensorflow:Using config: {'_model_dir': '/tmp/tmpl4yo66ty', '_tf_random_seed': 42, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': allow_soft_placement: true
graph_options {
  rewrite_options {
    meta_optimizer_iterations: ONE
  }
}
, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': None, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': None, '_experimental_max_worker_delay_secs': None, '_session_creation_timeout_secs': 7200, '_service': None, '_cluster_spec': ClusterSpec({}), '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}


In [30]:
regressor.train(input_fn = funcao_treinamento, steps = 10000)

Instructions for updating:
Use Variable.read_value. Variables in 2.X are initialized automatically both in eager and graph (inside tf.defun) contexts.
INFO:tensorflow:Calling model_fn.

If you intended to run this layer in float32, you can safely ignore this warning. If in doubt, this warning is likely only an issue if you are porting a TensorFlow 1.X model to TensorFlow 2.

To change all layers to have dtype float64 by default, call `tf.keras.backend.set_floatx('float64')`. To change just this layer, pass dtype='float64' to the layer constructor. If you are the author of this layer, you can disable autocasting by passing autocast=False to the base Layer constructor.

Instructions for updating:
Please use `layer.add_weight` method instead.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO:tensorf

In [31]:
metricas_treinamento = regressor.evaluate(input_fn = funcao_treinamento, steps = 10000)

INFO:tensorflow:Calling model_fn.

If you intended to run this layer in float32, you can safely ignore this warning. If in doubt, this warning is likely only an issue if you are porting a TensorFlow 1.X model to TensorFlow 2.

To change all layers to have dtype float64 by default, call `tf.keras.backend.set_floatx('float64')`. To change just this layer, pass dtype='float64' to the layer constructor. If you are the author of this layer, you can disable autocasting by passing autocast=False to the base Layer constructor.

INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Starting evaluation at 2020-09-04T20:54:47Z
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from /tmp/tmpl4yo66ty/model.ckpt-10000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Evaluation [1000/10000]
INFO:tensorflow:Evaluation [2000/10000]
INFO:tensorflow:Evaluation [3000/10000]
INFO:tensorflow:Evaluation [4000/10000]
INFO:tensorflow:Eva

In [32]:
metricas_teste = regressor.evaluate(input_fn = funcao_teste, steps = 10000)

INFO:tensorflow:Calling model_fn.

If you intended to run this layer in float32, you can safely ignore this warning. If in doubt, this warning is likely only an issue if you are porting a TensorFlow 1.X model to TensorFlow 2.

To change all layers to have dtype float64 by default, call `tf.keras.backend.set_floatx('float64')`. To change just this layer, pass dtype='float64' to the layer constructor. If you are the author of this layer, you can disable autocasting by passing autocast=False to the base Layer constructor.

INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Starting evaluation at 2020-09-04T20:54:57Z
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from /tmp/tmpl4yo66ty/model.ckpt-10000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Evaluation [1000/10000]
INFO:tensorflow:Evaluation [2000/10000]
INFO:tensorflow:Evaluation [3000/10000]
INFO:tensorflow:Evaluation [4000/10000]
INFO:tensorflow:Eva

In [33]:
metricas_treinamento

{'average_loss': 0.00068315916,
 'global_step': 10000,
 'label/mean': 0.06067819,
 'loss': 0.0006831179,
 'prediction/mean': 0.062800854}

In [34]:
metricas_teste

{'average_loss': 0.0007554067,
 'global_step': 10000,
 'label/mean': 0.061745208,
 'loss': 0.00076145254,
 'prediction/mean': 0.06365971}

In [35]:
funcao_previsao = make_input_fn(X_teste, num_epochs = 1, shuffle = False)

In [36]:
previsoes = regressor.predict(input_fn = funcao_previsao)

In [37]:
list(previsoes)

INFO:tensorflow:Calling model_fn.

If you intended to run this layer in float32, you can safely ignore this warning. If in doubt, this warning is likely only an issue if you are porting a TensorFlow 1.X model to TensorFlow 2.

To change all layers to have dtype float64 by default, call `tf.keras.backend.set_floatx('float64')`. To change just this layer, pass dtype='float64' to the layer constructor. If you are the author of this layer, you can disable autocasting by passing autocast=False to the base Layer constructor.

INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from /tmp/tmpl4yo66ty/model.ckpt-10000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.


[{'predictions': array([0.05124184], dtype=float32)},
 {'predictions': array([0.09058381], dtype=float32)},
 {'predictions': array([0.15378743], dtype=float32)},
 {'predictions': array([0.20975187], dtype=float32)},
 {'predictions': array([0.0882744], dtype=float32)},
 {'predictions': array([0.02916993], dtype=float32)},
 {'predictions': array([0.10037389], dtype=float32)},
 {'predictions': array([0.05891827], dtype=float32)},
 {'predictions': array([0.04263451], dtype=float32)},
 {'predictions': array([0.05554637], dtype=float32)},
 {'predictions': array([0.07444797], dtype=float32)},
 {'predictions': array([0.06738769], dtype=float32)},
 {'predictions': array([0.0332575], dtype=float32)},
 {'predictions': array([0.03716581], dtype=float32)},
 {'predictions': array([0.03141445], dtype=float32)},
 {'predictions': array([0.14630035], dtype=float32)},
 {'predictions': array([0.03364225], dtype=float32)},
 {'predictions': array([0.1389657], dtype=float32)},
 {'predictions': array([0.04300

In [38]:
valores_previsoes = []
for p in regressor.predict(input_fn = funcao_previsao):
    valores_previsoes.append(p['predictions'])

INFO:tensorflow:Calling model_fn.

If you intended to run this layer in float32, you can safely ignore this warning. If in doubt, this warning is likely only an issue if you are porting a TensorFlow 1.X model to TensorFlow 2.

To change all layers to have dtype float64 by default, call `tf.keras.backend.set_floatx('float64')`. To change just this layer, pass dtype='float64' to the layer constructor. If you are the author of this layer, you can disable autocasting by passing autocast=False to the base Layer constructor.

INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from /tmp/tmpl4yo66ty/model.ckpt-10000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.


In [39]:
valores_previsoes

[array([0.05124184], dtype=float32),
 array([0.09058381], dtype=float32),
 array([0.15378743], dtype=float32),
 array([0.20975187], dtype=float32),
 array([0.0882744], dtype=float32),
 array([0.02916993], dtype=float32),
 array([0.10037389], dtype=float32),
 array([0.05891827], dtype=float32),
 array([0.04263451], dtype=float32),
 array([0.05554637], dtype=float32),
 array([0.07444797], dtype=float32),
 array([0.06738769], dtype=float32),
 array([0.0332575], dtype=float32),
 array([0.03716581], dtype=float32),
 array([0.03141445], dtype=float32),
 array([0.14630035], dtype=float32),
 array([0.03364225], dtype=float32),
 array([0.1389657], dtype=float32),
 array([0.0430067], dtype=float32),
 array([0.07027254], dtype=float32),
 array([0.04804682], dtype=float32),
 array([0.16732389], dtype=float32),
 array([0.0889617], dtype=float32),
 array([0.10858553], dtype=float32),
 array([0.05033254], dtype=float32),
 array([0.06283321], dtype=float32),
 array([0.00729167], dtype=float32),
 array

In [40]:
import numpy as np
valores_previsoes = np.asarray(valores_previsoes).reshape(-1, 1)

In [41]:
valores_previsoes

array([[0.05124184],
       [0.09058381],
       [0.15378743],
       ...,
       [0.04395352],
       [0.09902368],
       [0.06656983]], dtype=float32)

In [42]:
valores_previsoes = scaler_y.inverse_transform(valores_previsoes)
valores_previsoes

array([[ 465719.06],
       [ 765701.5 ],
       [1247629.1 ],
       ...,
       [ 410145.62],
       [ 830055.5 ],
       [ 582594.94]], dtype=float32)

In [43]:
y_teste

735      0.038033
2830     0.103607
4106     0.126295
16218    0.185574
19964    0.083410
           ...   
12606    0.044197
14393    0.089836
6899     0.044000
85       0.113443
21363    0.043934
Name: price, Length: 6484, dtype: float64

In [44]:
y_teste.shape

(6484,)

In [45]:
y_teste2 = y_teste.values.reshape(-1, 1)
y_teste2.shape

(6484, 1)

In [46]:
y_teste2 = scaler_y.inverse_transform(y_teste2)

In [47]:
y_teste2

array([[ 365000.],
       [ 865000.],
       [1038000.],
       ...,
       [ 410500.],
       [ 940000.],
       [ 410000.]])

In [48]:
from sklearn.metrics import mean_absolute_error
mae = mean_absolute_error(y_teste2, valores_previsoes)

In [49]:
mae

129072.11275935761