In [1]:
import tensorflow as tf

In [2]:
a = tf.constant([[1,2], [3,4]])
b = tf.constant([[-1, 3], [4, 2]])

In [3]:
multiplicacao = tf.matmul(a, b)

In [4]:
print(a)
print('\n')
print(b)
print('\n')
print(multiplicacao)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


tf.Tensor(
[[-1  3]
 [ 4  2]], shape=(2, 2), dtype=int32)


tf.Tensor(
[[ 7  7]
 [13 17]], shape=(2, 2), dtype=int32)


In [5]:
multiplicacao2 = tf.matmul(b, a)

In [6]:
print(multiplicacao2)

tf.Tensor(
[[ 8 10]
 [10 16]], shape=(2, 2), dtype=int32)


In [7]:
a1 = tf.constant([[2,3],[0,1], [-1,4]])
b1 = tf.constant([[1,2,3], [-2,0,4]])
multiplicacao3 = tf.matmul(a1, b1)

In [8]:
print(a1)
print('\n')
print(b1)
print('\n')
print(multiplicacao3)

tf.Tensor(
[[ 2  3]
 [ 0  1]
 [-1  4]], shape=(3, 2), dtype=int32)


tf.Tensor(
[[ 1  2  3]
 [-2  0  4]], shape=(2, 3), dtype=int32)


tf.Tensor(
[[-4  4 18]
 [-2  0  4]
 [-9 -2 13]], shape=(3, 3), dtype=int32)
