# Operador OR

In [ ]:
import tensorflow as tf
import numpy as np
tf.__version__

'2.3.0'

In [ ]:
X = np.array([[0.0, 0.0],
              [0.0, 1.0],
              [1.0, 0.0],
              [1.0, 1.0]])
X

array([[0., 0.],
       [0., 1.],
       [1., 0.],
       [1., 1.]])

In [ ]:
y = np.array([[0.0], [1.0], [1.0], [1.0]])
y

array([[0.],
       [1.],
       [1.],
       [1.]])

In [ ]:
W = tf.Variable(tf.zeros([2, 1], dtype = tf.float64))
type(W)

tensorflow.python.ops.resource_variable_ops.ResourceVariable

In [ ]:
print(W)

<tf.Variable 'Variable:0' shape=(2, 1) dtype=float64, numpy=
array([[0.],
       [0.]])>


In [ ]:
def step(x):
    return tf.cast(tf.math.greater_equal(x, 1), tf.float64)

No TensorFlow 2.x, não existe o conceito de sessão; cada função roda logo que invocada (eager execution). Assim, podemos fazer o treinamento atualizando as variáveis chamando diretamente as funções. Também não existe `global_variables_initializer()`.

In [ ]:
epoca = 0
for i in range(15):
    epoca += 1
    
    # Forward pass
    camada_saida = tf.matmul(X, W)
    camada_saida_ativacao = step(camada_saida)
    
    # Backpropagation
    erro = tf.subtract(y, camada_saida_ativacao)
    delta = tf.matmul(X, erro, transpose_a = True)
    W.assign_add(tf.multiply(delta, 0.1))
    
    # Resumo da época
    erro_soma = tf.reduce_sum(erro).numpy()
    print('Época:', epoca, ' Erro: ', erro_soma)
    if erro_soma == 0.0:
        break

Época: 1  Erro:  3.0
Época: 2  Erro:  3.0
Época: 3  Erro:  3.0
Época: 4  Erro:  2.0
Época: 5  Erro:  2.0
Época: 6  Erro:  2.0
Época: 7  Erro:  2.0
Época: 8  Erro:  0.0


In [ ]:
W

<tf.Variable 'Variable:0' shape=(2, 1) dtype=float64, numpy=
array([[1.],
       [1.]])>

In [ ]:
W.numpy()

array([[1.],
       [1.]])

In [ ]:
# teste
camada_saida_teste = tf.matmul(X, W)
camada_saida_ativacao_teste = step(camada_saida_teste)
camada_saida_ativacao_teste.numpy()

array([[0.],
       [1.],
       [1.],
       [1.]])