# Operador OR

In [13]:
# pip install --upgrade tensorflow
#!pip install tf-nightly-gpu


In [1]:
import tensorflow as tf
import numpy as np
tf.__version__

2022-03-02 23:08:25.759221: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-03-02 23:08:25.759252: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.


'2.9.0-dev20220302'

In [6]:
X = np.array([[0.0, 0.0],
              [0.0, 1.0],
              [1.0, 0.0],
              [1.0, 1.0]])
X

array([[0., 0.],
       [0., 1.],
       [1., 0.],
       [1., 1.]])

In [7]:
y = np.array([[0.0], [1.0], [1.0], [1.0]])
y

array([[0.],
       [1.],
       [1.],
       [1.]])

In [4]:
W = tf.Variable(tf.zeros([2, 1], dtype = tf.float64))
type(W)

2022-03-02 23:08:36.377505: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2022-03-02 23:08:36.377549: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2022-03-02 23:08:36.377579: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (lucas): /proc/driver/nvidia/version does not exist


tensorflow.python.ops.resource_variable_ops.ResourceVariable

In [5]:
print(W)

<tf.Variable 'Variable:0' shape=(2, 1) dtype=float64, numpy=
array([[0.],
       [0.]])>


In [8]:
def step(x):
    return tf.cast(tf.math.greater_equal(x, 1), tf.float64)

No TensorFlow 2.x, não existe o conceito de sessão; cada função roda logo que invocada (eager execution). Assim, podemos fazer o treinamento atualizando as variáveis chamando diretamente as funções. Também não existe `global_variables_initializer()`.

In [9]:
epoca = 0
for i in range(15):
    epoca += 1
    
    # Forward pass
    camada_saida = tf.matmul(X, W)
    camada_saida_ativacao = step(camada_saida)
    
    # Backpropagation
    erro = tf.subtract(y, camada_saida_ativacao)
    delta = tf.matmul(X, erro, transpose_a = True)
    W.assign_add(tf.multiply(delta, 0.1))
    
    # Resumo da época
    erro_soma = tf.reduce_sum(erro).numpy()
    print('Época:', epoca, ' Erro: ', erro_soma)
    if erro_soma == 0.0:
        break

Época: 1  Erro:  3.0
Época: 2  Erro:  3.0
Época: 3  Erro:  3.0
Época: 4  Erro:  2.0
Época: 5  Erro:  2.0
Época: 6  Erro:  2.0
Época: 7  Erro:  2.0
Época: 8  Erro:  0.0


In [10]:
W

<tf.Variable 'Variable:0' shape=(2, 1) dtype=float64, numpy=
array([[1.],
       [1.]])>

In [11]:
W.numpy()

array([[1.],
       [1.]])

In [13]:
# teste
camada_saida_teste = tf.matmul(X, W)
camada_saida_ativacao_teste = step(camada_saida_teste)
camada_saida_ativacao_teste.numpy()

array([[0.],
       [1.],
       [1.],
       [1.]])