In [1]:
from sklearn import datasets
iris = datasets.load_iris()

X = iris.data
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [2]:
y = iris.target
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [3]:
from sklearn.preprocessing import StandardScaler
scaler_x = StandardScaler()
X = scaler_x.fit_transform(X)
X

array([[-9.00681170e-01,  1.01900435e+00, -1.34022653e+00,
        -1.31544430e+00],
       [-1.14301691e+00, -1.31979479e-01, -1.34022653e+00,
        -1.31544430e+00],
       [-1.38535265e+00,  3.28414053e-01, -1.39706395e+00,
        -1.31544430e+00],
       [-1.50652052e+00,  9.82172869e-02, -1.28338910e+00,
        -1.31544430e+00],
       [-1.02184904e+00,  1.24920112e+00, -1.34022653e+00,
        -1.31544430e+00],
       [-5.37177559e-01,  1.93979142e+00, -1.16971425e+00,
        -1.05217993e+00],
       [-1.50652052e+00,  7.88807586e-01, -1.34022653e+00,
        -1.18381211e+00],
       [-1.02184904e+00,  7.88807586e-01, -1.28338910e+00,
        -1.31544430e+00],
       [-1.74885626e+00, -3.62176246e-01, -1.34022653e+00,
        -1.31544430e+00],
       [-1.14301691e+00,  9.82172869e-02, -1.28338910e+00,
        -1.44707648e+00],
       [-5.37177559e-01,  1.47939788e+00, -1.28338910e+00,
        -1.31544430e+00],
       [-1.26418478e+00,  7.88807586e-01, -1.22655167e+00,
      

In [4]:
from sklearn.preprocessing import OneHotEncoder
onehot = OneHotEncoder()
y.shape

(150,)

In [5]:
y = y.reshape(-1, 1)
y.shape

(150, 1)

In [6]:
y = onehot.fit_transform(y).toarray()
y

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

In [7]:
from sklearn.model_selection import train_test_split
X_treinamento, X_teste, y_treinamento, y_teste = train_test_split(X, y, test_size = 0.3, random_state = 42)

In [8]:
X_treinamento.shape

(105, 4)

In [9]:
X_teste.shape

(45, 4)

In [10]:
import tensorflow as tf
import numpy as np

tf.random.set_seed(42)

tf.__version__

'2.3.0'

In [11]:
neuronios_entrada = X.shape[1]
neuronios_entrada

4

In [12]:
neuronios_oculta = int(np.ceil((X.shape[1] + y.shape[1]) / 2))
neuronios_oculta

4

In [13]:
neuronios_saida = y.shape[1]
neuronios_saida

3

In [14]:
W = {'oculta': tf.Variable(tf.random.normal([neuronios_entrada, neuronios_oculta])),
     'saida': tf.Variable(tf.random.normal([neuronios_oculta, neuronios_saida]))}

In [15]:
b = {'oculta': tf.Variable(tf.random.normal([neuronios_oculta])),
     'saida': tf.Variable(tf.random.normal([neuronios_saida]))}

In [16]:
X_treinamento = tf.convert_to_tensor(X_treinamento, dtype = tf.float32, name = 'X')
y_treinamento = tf.convert_to_tensor(y_treinamento, dtype = tf.float32, name = 'y')
X_teste = tf.convert_to_tensor(X_teste, dtype = tf.float32, name = 'X')
y_teste = tf.convert_to_tensor(y_teste, dtype = tf.float32, name = 'y')

In [17]:
def mlp(x, W, bias):
    camada_oculta = tf.add(tf.matmul(x, W['oculta']), bias['oculta'])
    camada_oculta_ativacao = tf.nn.relu(camada_oculta)
    camada_saida = tf.add(tf.matmul(camada_oculta_ativacao, W['saida']), b['saida'])
    return camada_saida

Exemplo de treinamento de uma época:

In [18]:
with tf.GradientTape() as tape:
    modelo = mlp(X_treinamento, W, b)
    erro = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(labels = y_treinamento, logits = modelo))

In [19]:
var_list = [W['oculta'], W['saida'], b['oculta'], b['saida']]

Verificando `W['oculta']` antes da atualização.

In [20]:
W['oculta']

<tf.Variable 'Variable:0' shape=(4, 4) dtype=float32, numpy=
array([[ 0.3274685 , -0.8426258 ,  0.3194337 , -1.4075519 ],
       [-2.3880599 , -1.0392479 , -0.5573232 ,  0.539707  ],
       [ 1.6994323 ,  0.28893656, -1.5066116 , -0.26454744],
       [-0.59722406, -1.9171132 , -0.62044144,  0.8504023 ]],
      dtype=float32)>

In [21]:
otimizador = tf.keras.optimizers.Adam(learning_rate = 0.0001)
gradientes = tape.gradient(erro, var_list)
otimizador.apply_gradients(zip(gradientes, var_list))

<tf.Variable 'UnreadVariable' shape=() dtype=int64, numpy=1>

Verificando `W['oculta']` depois da atualização. Perceba que alguns valores foram alterados.


In [22]:
W['oculta']

<tf.Variable 'Variable:0' shape=(4, 4) dtype=float32, numpy=
array([[ 0.3275685 , -0.8425258 ,  0.3193337 , -1.4074519 ],
       [-2.38796   , -1.0391479 , -0.55742323,  0.53960705],
       [ 1.6993322 ,  0.28903654, -1.5065116 , -0.26444745],
       [-0.59712404, -1.9170132 , -0.6203415 ,  0.8505023 ]],
      dtype=float32)>

### Treinamento

Como `X_treinamento` e `y_treinamento` já são tensores, vou convertê-los em um dataset para gerar batches.

In [23]:
dataset = tf.data.Dataset.from_tensor_slices((X_treinamento, y_treinamento))
dataset

<TensorSliceDataset shapes: ((4,), (3,)), types: (tf.float32, tf.float32)>

In [24]:
batch_size = 8
dataset = dataset.batch(batch_size)
dataset

<BatchDataset shapes: ((None, 4), (None, 3)), types: (tf.float32, tf.float32)>

Verificando o primeiro batch.

In [25]:
next(iter(dataset))

(<tf.Tensor: shape=(8, 4), dtype=float32, numpy=
 array([[-0.4160097 , -1.5131601 , -0.03296571, -0.26238683],
        [ 0.5533333 , -0.592373  ,  0.76275826,  0.3957741 ],
        [ 0.6745011 ,  0.09821729,  0.99010795,  0.79067063],
        [ 0.91683686, -0.13197948,  0.36489627,  0.26414192],
        [ 1.6438441 ,  1.249201  ,  1.3311325 ,  1.712096  ],
        [-0.17367394, -0.36217624,  0.25122142,  0.13250974],
        [ 2.1285155 , -0.13197948,  1.6153197 ,  1.1855673 ],
        [-0.29484183, -0.13197948,  0.4217337 ,  0.3957741 ]],
       dtype=float32)>, <tf.Tensor: shape=(8, 3), dtype=float32, numpy=
 array([[0., 1., 0.],
        [0., 0., 1.],
        [0., 0., 1.],
        [0., 1., 0.],
        [0., 0., 1.],
        [0., 1., 0.],
        [0., 0., 1.],
        [0., 1., 0.]], dtype=float32)>)

Agora precisamos instanciar o dataset de novo para ele reiniciar a geração de batches.

In [26]:
dataset = tf.data.Dataset.from_tensor_slices((X_treinamento, y_treinamento)).batch(batch_size)

In [27]:
for epoca in range(3000):
    for X_batch, y_batch in dataset:
        erro_medio = 0.0
        with tf.GradientTape() as tape:
            modelo = mlp(X_batch, W, b)
            erro = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(labels = y_batch, logits = modelo))
        gradientes = tape.gradient(erro, var_list)
        otimizador.apply_gradients(zip(gradientes, var_list))
        erro_medio += erro.numpy()
    if epoca % 500 == 0:
        print('Época: ' + str((epoca + 1)) + ' erro: ' + str(erro_medio))

Época: 1 erro: 0.6721729636192322
Época: 501 erro: 0.0862426906824112
Época: 1001 erro: 0.013050147332251072
Época: 1501 erro: 0.007997041568160057
Época: 2001 erro: 0.005524486768990755
Época: 2501 erro: 0.0037681306712329388


In [28]:
W

{'oculta': <tf.Variable 'Variable:0' shape=(4, 4) dtype=float32, numpy=
 array([[ 0.4611652 , -1.1641408 ,  0.7611367 , -2.2196932 ],
        [-2.146431  ,  0.12059374, -0.8854005 ,  1.1447481 ],
        [ 2.7273316 , -1.1449347 , -1.5382882 , -1.5425806 ],
        [ 0.93908817, -3.28057   , -1.3536494 , -0.48376253]],
       dtype=float32)>,
 'saida': <tf.Variable 'Variable:0' shape=(4, 3) dtype=float32, numpy=
 array([[-2.3901334 , -0.6245917 ,  0.9601594 ],
        [ 1.3585486 , -1.0920751 , -1.1838957 ],
        [-1.3694073 ,  1.0534822 , -1.5046941 ],
        [ 0.24990483, -3.1377513 , -2.0557623 ]], dtype=float32)>}

In [29]:
b

{'oculta': <tf.Variable 'Variable:0' shape=(4,) dtype=float32, numpy=array([-0.46551293, -0.8191203 ,  3.0532377 , -0.8415136 ], dtype=float32)>,
 'saida': <tf.Variable 'Variable:0' shape=(3,) dtype=float32, numpy=array([-1.4360176 ,  0.22936691,  0.48931423], dtype=float32)>}

In [30]:
# previsões
previsoes_teste = mlp(X_teste, W, b)
previsoes_teste

<tf.Tensor: shape=(45, 3), dtype=float32, numpy=
array([[-11.291361  ,   1.873344  ,  -1.6947509 ],
       [ -0.51520216, -12.127889  , -20.416489  ],
       [-24.452103  ,  -4.3889246 ,   7.702383  ],
       [ -9.224229  ,   1.4880748 ,  -1.1777575 ],
       [-13.463988  ,   1.5903668 ,  -1.2365812 ],
       [ -1.2678763 , -11.150146  , -20.955662  ],
       [ -5.824955  ,   3.4692554 ,  -4.1344643 ],
       [-10.55897   ,  -1.0167767 ,   2.4975014 ],
       [-19.964464  ,   0.955324  ,  -0.17384979],
       [ -9.965686  ,   3.104113  ,  -3.51484   ],
       [ -7.9051456 ,  -0.37714273,   1.509837  ],
       [  0.57854784, -15.138429  , -26.490438  ],
       [ -0.57202923, -12.602413  , -23.240648  ],
       [  0.5854944 , -14.861129  , -25.788374  ],
       [  1.7768096 , -19.206722  , -24.680977  ],
       [ -4.7164755 ,   1.4076434 ,  -1.1564568 ],
       [-12.683619  ,  -2.4172804 ,   4.5816927 ],
       [-12.314687  ,   3.0567324 ,  -3.3959346 ],
       [ -9.801856  ,   1.7372541

In [31]:
previsoes_teste = tf.nn.softmax(previsoes_teste)
previsoes_teste

<tf.Tensor: shape=(45, 3), dtype=float32, numpy=
array([[1.8644841e-06, 9.7256255e-01, 2.7435552e-02],
       [9.9999094e-01, 9.0504582e-06, 2.2749764e-09],
       [1.0851282e-14, 5.6080180e-06, 9.9999440e-01],
       [2.0820886e-05, 9.3496066e-01, 6.5018527e-02],
       [2.7352758e-07, 9.4411457e-01, 5.5885188e-02],
       [9.9994898e-01, 5.1069663e-05, 2.8163136e-09],
       [9.1900802e-05, 9.9940979e-01, 4.9829908e-04],
       [2.0744621e-06, 2.8908638e-02, 9.7108924e-01],
       [6.2085898e-10, 7.5568640e-01, 2.4431361e-01],
       [2.1051255e-06, 9.9866486e-01, 1.3330459e-03],
       [7.0765142e-05, 1.3157989e-01, 8.6834931e-01],
       [9.9999988e-01, 1.4934956e-07, 1.7542373e-12],
       [9.9999404e-01, 5.9602985e-06, 1.4293587e-10],
       [9.9999976e-01, 1.9571173e-07, 3.5153954e-12],
       [1.0000000e+00, 7.7084650e-10, 3.2324315e-12],
       [2.0287849e-03, 9.2663133e-01, 7.1339883e-02],
       [3.1722973e-08, 9.1198651e-04, 9.9908793e-01],
       [2.1066552e-07, 9.9842596e

In [32]:
previsoes_teste = tf.argmax(previsoes_teste, axis = 1).numpy()
previsoes_teste

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0])

In [33]:
y_teste2 = tf.argmax(y_teste, axis = 1).numpy()
y_teste2

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0])

In [34]:
from sklearn.metrics import accuracy_score
taxa_acerto = accuracy_score(y_teste2, previsoes_teste)
taxa_acerto

1.0