In [1]:
from sklearn import datasets
iris = datasets.load_iris()

X = iris.data
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [2]:
y = iris.target
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [3]:
from sklearn.preprocessing import StandardScaler
scaler_x = StandardScaler()
X = scaler_x.fit_transform(X)
X

array([[-9.00681170e-01,  1.01900435e+00, -1.34022653e+00,
        -1.31544430e+00],
       [-1.14301691e+00, -1.31979479e-01, -1.34022653e+00,
        -1.31544430e+00],
       [-1.38535265e+00,  3.28414053e-01, -1.39706395e+00,
        -1.31544430e+00],
       [-1.50652052e+00,  9.82172869e-02, -1.28338910e+00,
        -1.31544430e+00],
       [-1.02184904e+00,  1.24920112e+00, -1.34022653e+00,
        -1.31544430e+00],
       [-5.37177559e-01,  1.93979142e+00, -1.16971425e+00,
        -1.05217993e+00],
       [-1.50652052e+00,  7.88807586e-01, -1.34022653e+00,
        -1.18381211e+00],
       [-1.02184904e+00,  7.88807586e-01, -1.28338910e+00,
        -1.31544430e+00],
       [-1.74885626e+00, -3.62176246e-01, -1.34022653e+00,
        -1.31544430e+00],
       [-1.14301691e+00,  9.82172869e-02, -1.28338910e+00,
        -1.44707648e+00],
       [-5.37177559e-01,  1.47939788e+00, -1.28338910e+00,
        -1.31544430e+00],
       [-1.26418478e+00,  7.88807586e-01, -1.22655167e+00,
      

In [4]:
from sklearn.preprocessing import OneHotEncoder
onehot = OneHotEncoder()
y.shape

(150,)

In [5]:
y = y.reshape(-1, 1)
y.shape

(150, 1)

In [6]:
y = onehot.fit_transform(y).toarray()
y

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

In [7]:
from sklearn.model_selection import train_test_split
X_treinamento, X_teste, y_treinamento, y_teste = train_test_split(X, y, test_size = 0.3, random_state = 42)

In [8]:
X_treinamento.shape

(105, 4)

In [9]:
X_teste.shape

(45, 4)

In [10]:
import tensorflow as tf
import numpy as np

tf.random.set_seed(42)

tf.__version__

2022-06-20 20:32:22.750196: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-06-20 20:32:22.750212: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.


'2.9.0'

In [11]:
neuronios_entrada = X.shape[1]
neuronios_entrada

4

In [12]:
neuronios_oculta = int(np.ceil((X.shape[1] + y.shape[1]) / 2))
neuronios_oculta

4

In [13]:
y.shape

(150, 3)

In [14]:
neuronios_saida = y.shape[1]
neuronios_saida

3

In [15]:
W = {'oculta': tf.Variable(tf.random.normal([neuronios_entrada, neuronios_oculta])),
     'saida': tf.Variable(tf.random.normal([neuronios_oculta, neuronios_saida]))}

2022-06-20 20:32:23.923901: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2022-06-20 20:32:23.923967: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2022-06-20 20:32:23.924029: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (lucas): /proc/driver/nvidia/version does not exist
2022-06-20 20:32:23.924474: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [16]:
b = {'oculta': tf.Variable(tf.random.normal([neuronios_oculta])),
     'saida': tf.Variable(tf.random.normal([neuronios_saida]))}

In [17]:
X_treinamento = tf.convert_to_tensor(X_treinamento, dtype = tf.float32, name = 'X')
y_treinamento = tf.convert_to_tensor(y_treinamento, dtype = tf.float32, name = 'y')
X_teste = tf.convert_to_tensor(X_teste, dtype = tf.float32, name = 'X')
y_teste = tf.convert_to_tensor(y_teste, dtype = tf.float32, name = 'y')

In [18]:
def mlp(x, W, bias):
    camada_oculta = tf.add(tf.matmul(x, W['oculta']), bias['oculta'])
    camada_oculta_ativacao = tf.nn.relu(camada_oculta)
    camada_saida = tf.add(tf.matmul(camada_oculta_ativacao, W['saida']), b['saida'])
    return camada_saida

Exemplo de treinamento de uma época:

In [19]:
with tf.GradientTape() as tape:
    modelo = mlp(X_treinamento, W, b)
    erro = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(labels = y_treinamento, logits = modelo))

In [20]:
var_list = [W['oculta'], W['saida'], b['oculta'], b['saida']]

Verificando `W['oculta']` antes da atualização.

In [21]:
W['oculta']

<tf.Variable 'Variable:0' shape=(4, 4) dtype=float32, numpy=
array([[ 0.3274685 , -0.8426258 ,  0.3194337 , -1.4075519 ],
       [-2.3880599 , -1.0392479 , -0.5573232 ,  0.539707  ],
       [ 1.6994323 ,  0.28893656, -1.5066116 , -0.26454744],
       [-0.59722406, -1.9171132 , -0.62044144,  0.8504023 ]],
      dtype=float32)>

In [22]:
otimizador = tf.keras.optimizers.Adam(learning_rate = 0.0001)
gradientes = tape.gradient(erro, var_list)
otimizador.apply_gradients(zip(gradientes, var_list))

<tf.Variable 'UnreadVariable' shape=() dtype=int64, numpy=1>

Verificando `W['oculta']` depois da atualização. Perceba que alguns valores foram alterados.


In [23]:
W['oculta']

<tf.Variable 'Variable:0' shape=(4, 4) dtype=float32, numpy=
array([[ 0.3275685 , -0.8425258 ,  0.3193337 , -1.4074519 ],
       [-2.38796   , -1.0391479 , -0.55742323,  0.53960705],
       [ 1.6993322 ,  0.28903654, -1.5065116 , -0.26444745],
       [-0.59712404, -1.9170132 , -0.6203415 ,  0.8505023 ]],
      dtype=float32)>

### Treinamento

Como `X_treinamento` e `y_treinamento` já são tensores, vou convertê-los em um dataset para gerar batches.

In [24]:
dataset = tf.data.Dataset.from_tensor_slices((X_treinamento, y_treinamento))
dataset

<TensorSliceDataset element_spec=(TensorSpec(shape=(4,), dtype=tf.float32, name=None), TensorSpec(shape=(3,), dtype=tf.float32, name=None))>

In [25]:
batch_size = 8
dataset = dataset.batch(batch_size)
dataset

<BatchDataset element_spec=(TensorSpec(shape=(None, 4), dtype=tf.float32, name=None), TensorSpec(shape=(None, 3), dtype=tf.float32, name=None))>

Verificando o primeiro batch.

In [26]:
next(iter(dataset))

(<tf.Tensor: shape=(8, 4), dtype=float32, numpy=
 array([[-0.4160097 , -1.5131601 , -0.03296571, -0.26238683],
        [ 0.5533333 , -0.592373  ,  0.76275826,  0.3957741 ],
        [ 0.6745011 ,  0.09821729,  0.99010795,  0.79067063],
        [ 0.91683686, -0.13197948,  0.36489627,  0.26414192],
        [ 1.6438441 ,  1.249201  ,  1.3311325 ,  1.712096  ],
        [-0.17367394, -0.36217624,  0.25122142,  0.13250974],
        [ 2.1285155 , -0.13197948,  1.6153197 ,  1.1855673 ],
        [-0.29484183, -0.13197948,  0.4217337 ,  0.3957741 ]],
       dtype=float32)>,
 <tf.Tensor: shape=(8, 3), dtype=float32, numpy=
 array([[0., 1., 0.],
        [0., 0., 1.],
        [0., 0., 1.],
        [0., 1., 0.],
        [0., 0., 1.],
        [0., 1., 0.],
        [0., 0., 1.],
        [0., 1., 0.]], dtype=float32)>)

Agora precisamos instanciar o dataset de novo para ele reiniciar a geração de batches.

In [27]:
dataset = tf.data.Dataset.from_tensor_slices((X_treinamento, y_treinamento)).batch(batch_size)

In [28]:
for epoca in range(3000):
    for X_batch, y_batch in dataset:
        erro_medio = 0.0
        with tf.GradientTape() as tape:
            modelo = mlp(X_batch, W, b)
            erro = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(labels = y_batch, logits = modelo))
        gradientes = tape.gradient(erro, var_list)
        otimizador.apply_gradients(zip(gradientes, var_list))
        erro_medio += erro.numpy()
    if epoca % 500 == 0:
        print('Época: ' + str((epoca + 1)) + ' erro: ' + str(erro_medio))

Época: 1 erro: 0.6721729636192322
Época: 501 erro: 0.08624257892370224
Época: 1001 erro: 0.013050147332251072
Época: 1501 erro: 0.007997041568160057
Época: 2001 erro: 0.005524486768990755
Época: 2501 erro: 0.0037681306712329388


In [29]:
W

{'oculta': <tf.Variable 'Variable:0' shape=(4, 4) dtype=float32, numpy=
 array([[ 0.4611653 , -1.1641417 ,  0.76113683, -2.219693  ],
        [-2.1464312 ,  0.12059354, -0.8854009 ,  1.1447479 ],
        [ 2.7273316 , -1.1449343 , -1.5382881 , -1.5425805 ],
        [ 0.9390881 , -3.2805703 , -1.3536493 , -0.4837626 ]],
       dtype=float32)>,
 'saida': <tf.Variable 'Variable:0' shape=(4, 3) dtype=float32, numpy=
 array([[-2.3901331 , -0.62459177,  0.9601594 ],
        [ 1.3585486 , -1.0920748 , -1.1838961 ],
        [-1.3694073 ,  1.0534819 , -1.5046939 ],
        [ 0.24990495, -3.1377509 , -2.055762  ]], dtype=float32)>}

In [30]:
b

{'oculta': <tf.Variable 'Variable:0' shape=(4,) dtype=float32, numpy=array([-0.46551317, -0.8191202 ,  3.0532377 , -0.8415136 ], dtype=float32)>,
 'saida': <tf.Variable 'Variable:0' shape=(3,) dtype=float32, numpy=array([-1.4360179 ,  0.22936687,  0.48931447], dtype=float32)>}

In [31]:
# previsões
previsoes_teste = mlp(X_teste, W, b)
previsoes_teste

<tf.Tensor: shape=(45, 3), dtype=float32, numpy=
array([[-11.291361  ,   1.8733435 ,  -1.6947504 ],
       [ -0.515201  , -12.127883  , -20.416485  ],
       [-24.452103  ,  -4.388924  ,   7.702382  ],
       [ -9.224228  ,   1.4880744 ,  -1.1777574 ],
       [-13.463988  ,   1.5903661 ,  -1.2365807 ],
       [ -1.2678765 , -11.150144  , -20.955662  ],
       [ -5.824955  ,   3.4692545 ,  -4.134463  ],
       [-10.558969  ,  -1.0167767 ,   2.4975011 ],
       [-19.964464  ,   0.9553236 ,  -0.17385009],
       [ -9.965686  ,   3.1041121 ,  -3.5148392 ],
       [ -7.905145  ,  -0.37714294,   1.5098372 ],
       [  0.57854855, -15.138425  , -26.490437  ],
       [ -0.572029  , -12.602409  , -23.240646  ],
       [  0.585497  , -14.861127  , -25.788372  ],
       [  1.7768127 , -19.206717  , -24.680971  ],
       [ -4.7164745 ,   1.4076432 ,  -1.1564566 ],
       [-12.683618  ,  -2.4172802 ,   4.581692  ],
       [-12.314688  ,   3.0567312 ,  -3.3959339 ],
       [ -9.801855  ,   1.7372538

In [32]:
previsoes_teste = tf.nn.softmax(previsoes_teste)
previsoes_teste

<tf.Tensor: shape=(45, 3), dtype=float32, numpy=
array([[1.86448597e-06, 9.72562551e-01, 2.74355784e-02],
       [9.99990880e-01, 9.05049183e-06, 2.27498509e-09],
       [1.08513213e-14, 5.60802300e-06, 9.99994338e-01],
       [2.08209040e-05, 9.34960604e-01, 6.50185496e-02],
       [2.73527803e-07, 9.44114447e-01, 5.58852628e-02],
       [9.99948919e-01, 5.10697573e-05, 2.81631318e-09],
       [9.19008962e-05, 9.99409795e-01, 4.98300244e-04],
       [2.07446578e-06, 2.89086364e-02, 9.71089184e-01],
       [6.20858975e-10, 7.55686402e-01, 2.44313642e-01],
       [2.10512962e-06, 9.98664856e-01, 1.33304787e-03],
       [7.07652143e-05, 1.31579876e-01, 8.68349314e-01],
       [9.99999821e-01, 1.49349972e-07, 1.75424042e-12],
       [9.99993980e-01, 5.96032078e-06, 1.42936135e-10],
       [9.99999702e-01, 1.95711522e-07, 3.51539501e-12],
       [9.99999940e-01, 7.70847830e-10, 3.23243732e-12],
       [2.02878681e-03, 9.26631272e-01, 7.13399127e-02],
       [3.17230331e-08, 9.11986979e-04,

In [33]:
previsoes_teste = tf.argmax(previsoes_teste, axis = 1).numpy()
previsoes_teste

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0])

In [34]:
y_teste2 = tf.argmax(y_teste, axis = 1).numpy()
y_teste2

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0])

In [35]:
from sklearn.metrics import accuracy_score
taxa_acerto = accuracy_score(y_teste2, previsoes_teste)
taxa_acerto

1.0